### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [mapbox/storytelling#26]
Dear all,

First of all thank you for the amazing template!

Unfortunately, the doc is quite minimal and does not explain where the layers in the `config.js` come from. I have had a look at the example but they are defined in the `config.js` but nowhere else.

Can you please guide me to create a custom layer (e.g. maybe a region highlighted in red?). Then I could update the README properly to also include a deeper explanation on that part.

Thank you :)

Cheers,

Francesco Saverio Zuppichini

**Comment by mehdibaha** [comment]
Hello,

I am not an expert on scrollytelling with Mapbox, but I just completed [my first project](covid.mehdibaha.com/en/) with it ([git repo](https://github.com/mehdibaha/covid-map)) so I started to get the hang of it:
- You need to create your chapter in config.js and give a layer id to your chapter
- You need to define opacity transitions (normally, you set opacity to 0.x when entering a chapter, and you need to set it to 0.0 when exiting)
- You need to go to [Mapbox Studio][https://studio.mapbox.com/) and create *a new style there*, then publish it immediately. Mapbox then gives you a link that you can put in your config.js
- You can then create your first layers at the left of Studio.
* Every layer needs some data (preferably geojson, but also csv with lat/longs), then you need to style the data, by converting it either to colored markers, heatmaps, text labels, or even surface extrusions.
* If you want to style your points/polygons proportionally to some data, be sure to add it to each feature property in geojson, or in a csv column.
- When you have finished styling your layer, be sure to set its opacity to 0.0, so that it can be viewed only when it's the start of the corresponding chapter.

Hope this was clear enough, feel free to add any questions if you need :)

Stay safe,
Mehdi
