### ISSUE TITLE
Changing a layer

### ISSUE THREAD

**Issue by dsaad68** [mapbox/storytelling#5]
When I change a layer in a chapter, the layer in my story doesn't get updated.

**Comment by lobenichou** [comment]
Could you share some code with us?

**Comment by OneTimeUser** [comment]
Experiencing the same issue. Really the tutorial is simple but can't imagine what is happening beyond an issue with the layer name. 
Here is the example layer as it looks in Studio:
![Screen Shot 2020-11-24 at 4 02 29 PM](https://user-images.githubusercontent.com/418624/100151080-80a00280-2e55-11eb-875d-2dda7e99ca50.png)

I assume the name for the layer I am activating and deactivating is 'meteors'. It's set opacity is '0' since I want it to be visible upon entering a chapter. 

Below is an example of the step or chapter I am activating it.
```
...
onChapterEnter: [
                {
                    layer: 'meteors',
                    opacity: 1
                }
            ],
            onChapterExit: [
                {
                    layer: 'meteors',
                    opacity: 0
                }
            ]
...
```
I used the tutorial and template files from this link:
https://www.mapbox.com/solutions/interactive-storytelling
