### ISSUE TITLE
Issue with Storytelling when using Globe view (inset map issue)?

### ISSUE THREAD

**Issue by philiplugt** [mapbox/storytelling#54]
I have been experimenting using the new Globe view projection. Storytelling, or possibly Scrollama, seems have trouble with this new projection. 

The issue is, when scrolling between the chapters (as defined in config.js), flyTo/easeTo proceed to change the camera angle. It does so for a couple of frames, and then halts. As a result the next chapter's content have loaded, but the camera angle is still nearly in the original starting position. Note: scrolling up/down continuously will trigger the camera angle to move a couple more frame, but continuously halts.

Edit: Scrolling backwards from the last chapter globe view seems to work fine.

**Comment by pxv8780** [comment]
I have been able to pinpoint the issue. It occurs when to using Globe view projection alongside an inset map. Thus, if the inset map is false, the camera works fine. But with inset map set to true, the camera breaks when scrolling with globe view.

**Comment by pxv8780** [comment]
I have been testing and trying to recreate the issue. First thing to note, the issue is **gone/fixed** in the newly released GL JS v2.9.1.

It seems to occur in the older version of GL JS I was using, when I was testing globe view (v2.9.0 beta version 1 or 2). I added a GIF below (sorry for low quality), the error that is triggered is "bounds is null". So maybe there is a mix up between the bounds of the map and inset?

Anyway, here is an example, notice how in the first part of the GIF the camera barely moves/stutters on scrolling, the inset map moves correctly for the first chapter, then also stutters. In the second part of the GIF without the inset, the camera moves fine.

![inset_issue](https://user-images.githubusercontent.com/22942635/177319052-1712097f-6194-4f6d-a42a-3886bc325789.gif)

( Correction, the second part of the GIF where the zoom works should read "inset: false," )

Since the issue gone in v.2.9.1, this can be closed.
